name: docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          tags: ghcr.io/datafuselabs/fusebots:latest
